name: C++ g++ CI Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check g++ version
        run:  g++ --version

      - name: Compile Application
        run:  |
          mkdir -p bin
          g++ -std=c++17 firmware/src/main.cpp firmware/src/smartdeciion.cpp -Iinclude -o bin/app

      - name: Compile and Run Tests
        run:  |
          g++ -std=c++17 firmware/unit_test/unit_test.cpp firmware/src/smartdecission.cpp -Iinclude -o bin/run_test
          ./bin/run_test